/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author andre
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormDialog = new javax.swing.JDialog();
        BackgroundFD = new javax.swing.JPanel();
        FormTexts = new javax.swing.JPanel();
        UserVar = new javax.swing.JLabel();
        PassVar = new javax.swing.JLabel();
        UserCliente = new java.awt.TextField();
        PasswordCliente = new javax.swing.JPasswordField();
        ButtonsFM = new javax.swing.JPanel();
        Accept = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        UserInformation = new javax.swing.JDialog();
        BackgroundUI = new javax.swing.JPanel();
        BotonUI = new javax.swing.JPanel();
        DatosUI = new javax.swing.JPanel();
        NombreUI = new javax.swing.JLabel();
        TextNombreUI = new java.awt.TextField();
        ApellidoUI = new javax.swing.JLabel();
        TextApellidoUI = new java.awt.TextField();
        DireccionUI = new javax.swing.JLabel();
        TextDireccionUI = new java.awt.TextField();
        EmailUI = new javax.swing.JLabel();
        TextEmaiUI = new java.awt.TextField();
        TablaFull = new javax.swing.JPanel();
        BackUI = new javax.swing.JButton();
        ScrollTableCT = new javax.swing.JScrollPane();
        TableCT = new javax.swing.JTable();
        Empresa = new javax.swing.JDialog();
        BackgroundCT = new javax.swing.JPanel();
        BackCT = new javax.swing.JButton();
        Donaciones = new java.awt.Label();
        Realizamos = new java.awt.Label();
        CompanyName = new javax.swing.JLabel();
        ComidasReparto = new java.awt.Label();
        MenuDia = new javax.swing.JDialog();
        BackgroundMD = new javax.swing.JPanel();
        BotonesMD = new javax.swing.JPanel();
        BackMD = new javax.swing.JButton();
        Tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMD = new javax.swing.JTable();
        Menu = new javax.swing.JPanel();
        Form = new javax.swing.JButton();
        DatosCliente = new javax.swing.JButton();
        MenuRestaurante = new javax.swing.JButton();
        EmpresaButton = new javax.swing.JButton();

        FormDialog.setAlwaysOnTop(true);

        BackgroundFD.setBackground(new java.awt.Color(255, 255, 255));

        FormTexts.setBackground(new java.awt.Color(255, 255, 255));

        UserVar.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        UserVar.setText("Usuario");

        PassVar.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        PassVar.setText("Contraseña");

        UserCliente.setText("Andres");
        UserCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserClienteActionPerformed(evt);
            }
        });

        PasswordCliente.setText("AndresitoComunica");

        javax.swing.GroupLayout FormTextsLayout = new javax.swing.GroupLayout(FormTexts);
        FormTexts.setLayout(FormTextsLayout);
        FormTextsLayout.setHorizontalGroup(
            FormTextsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormTextsLayout.createSequentialGroup()
                .addGroup(FormTextsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PassVar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addGroup(FormTextsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordCliente))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        FormTextsLayout.setVerticalGroup(
            FormTextsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormTextsLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(FormTextsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserVar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(FormTextsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassVar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ButtonsFM.setBackground(new java.awt.Color(255, 255, 255));

        Accept.setBackground(new java.awt.Color(153, 255, 255));
        Accept.setText("Aceptar");
        ButtonsFM.add(Accept);

        Back.setBackground(new java.awt.Color(153, 255, 255));
        Back.setText("Volver");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        ButtonsFM.add(Back);

        javax.swing.GroupLayout BackgroundFDLayout = new javax.swing.GroupLayout(BackgroundFD);
        BackgroundFD.setLayout(BackgroundFDLayout);
        BackgroundFDLayout.setHorizontalGroup(
            BackgroundFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundFDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FormTexts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(BackgroundFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundFDLayout.createSequentialGroup()
                    .addComponent(ButtonsFM, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 72, Short.MAX_VALUE)))
        );
        BackgroundFDLayout.setVerticalGroup(
            BackgroundFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundFDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormTexts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(BackgroundFDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundFDLayout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(ButtonsFM, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout FormDialogLayout = new javax.swing.GroupLayout(FormDialog.getContentPane());
        FormDialog.getContentPane().setLayout(FormDialogLayout);
        FormDialogLayout.setHorizontalGroup(
            FormDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundFD, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        FormDialogLayout.setVerticalGroup(
            FormDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        BackgroundUI.setBackground(new java.awt.Color(255, 255, 255));

        BotonUI.setBackground(new java.awt.Color(255, 255, 255));

        DatosUI.setBackground(new java.awt.Color(255, 255, 255));
        DatosUI.setLayout(new java.awt.GridLayout(4, 2, 0, 40));

        NombreUI.setText("Nombre");
        DatosUI.add(NombreUI);

        TextNombreUI.setText("Andres");
        TextNombreUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreUIActionPerformed(evt);
            }
        });
        DatosUI.add(TextNombreUI);

        ApellidoUI.setText("Apellido");
        DatosUI.add(ApellidoUI);

        TextApellidoUI.setText("Ruiz Delgado");
        DatosUI.add(TextApellidoUI);

        DireccionUI.setText("Direccion");
        DatosUI.add(DireccionUI);

        TextDireccionUI.setText("C/Francisco Garrido Nº89");
        DatosUI.add(TextDireccionUI);

        EmailUI.setText("Email");
        DatosUI.add(EmailUI);

        TextEmaiUI.setText("andresruizdelgado12@gmail.com");
        DatosUI.add(TextEmaiUI);

        TablaFull.setLayout(new javax.swing.BoxLayout(TablaFull, javax.swing.BoxLayout.Y_AXIS));

        BackUI.setBackground(new java.awt.Color(204, 255, 255));
        BackUI.setText("Volver");
        BackUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackUIMouseClicked(evt);
            }
        });

        TableCT.setBackground(new java.awt.Color(204, 255, 255));
        TableCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Andres", "Ruiz Delgado", "Francisco Garrido Nº89", "andresruizdelgado12@gmail.com"},
                {"Javier", "Campos Cueva", "Carmina", "yoquese@gmail.com"},
                {"Marco", "Palmero Monroy", "Alguna parte de Sevilla", "marquitoershulo2001@gmail.com"},
                {"Javier", "Esmerado Vela", "Bormujos", "illoooquetemetounapataytedejonuevo@gmail.com"},
                {"vfsvs", "esfs", "sfessefs", "sfefs@gmail.com"},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Direccion", "Email"
            }
        ));
        ScrollTableCT.setViewportView(TableCT);

        javax.swing.GroupLayout BackgroundUILayout = new javax.swing.GroupLayout(BackgroundUI);
        BackgroundUI.setLayout(BackgroundUILayout);
        BackgroundUILayout.setHorizontalGroup(
            BackgroundUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundUILayout.createSequentialGroup()
                .addComponent(DatosUI, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ScrollTableCT, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(BackgroundUILayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(BackUI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundUILayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(BotonUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(BackgroundUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundUILayout.createSequentialGroup()
                    .addGap(468, 468, 468)
                    .addComponent(TablaFull, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BackgroundUILayout.setVerticalGroup(
            BackgroundUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundUILayout.createSequentialGroup()
                .addGroup(BackgroundUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DatosUI, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollTableCT, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BackUI)
                .addGap(18, 18, 18))
            .addGroup(BackgroundUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundUILayout.createSequentialGroup()
                    .addContainerGap(259, Short.MAX_VALUE)
                    .addComponent(BotonUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(BackgroundUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundUILayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(TablaFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout UserInformationLayout = new javax.swing.GroupLayout(UserInformation.getContentPane());
        UserInformation.getContentPane().setLayout(UserInformationLayout);
        UserInformationLayout.setHorizontalGroup(
            UserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UserInformationLayout.setVerticalGroup(
            UserInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInformationLayout.createSequentialGroup()
                .addComponent(BackgroundUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        BackgroundCT.setBackground(new java.awt.Color(255, 255, 255));

        BackCT.setBackground(new java.awt.Color(204, 255, 255));
        BackCT.setText("Atras");
        BackCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackCTMouseClicked(evt);
            }
        });
        BackCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackCTActionPerformed(evt);
            }
        });

        Donaciones.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        Donaciones.setText("DONACIONES");

        Realizamos.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Realizamos.setName(""); // NOI18N
        Realizamos.setText("REALIZAMOS:");

        CompanyName.setBackground(new java.awt.Color(255, 255, 255));
        CompanyName.setFont(new java.awt.Font("Trebuchet MS", 3, 48)); // NOI18N
        CompanyName.setForeground(new java.awt.Color(0, 0, 0));
        CompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompanyName.setText("Andresa Company");

        ComidasReparto.setFont(new java.awt.Font("Dialog", 2, 24)); // NOI18N
        ComidasReparto.setText("REPARTO DE COMIDAS");

        javax.swing.GroupLayout BackgroundCTLayout = new javax.swing.GroupLayout(BackgroundCT);
        BackgroundCT.setLayout(BackgroundCTLayout);
        BackgroundCTLayout.setHorizontalGroup(
            BackgroundCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCTLayout.createSequentialGroup()
                .addGroup(BackgroundCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCTLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundCTLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(Realizamos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundCTLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Donaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(ComidasReparto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(BackgroundCTLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(BackCT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundCTLayout.setVerticalGroup(
            BackgroundCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCTLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Realizamos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgroundCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCTLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComidasReparto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(BackgroundCTLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Donaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addComponent(BackCT, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout EmpresaLayout = new javax.swing.GroupLayout(Empresa.getContentPane());
        Empresa.getContentPane().setLayout(EmpresaLayout);
        EmpresaLayout.setHorizontalGroup(
            EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        EmpresaLayout.setVerticalGroup(
            EmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        BackgroundMD.setBackground(new java.awt.Color(255, 255, 255));

        BotonesMD.setBackground(new java.awt.Color(255, 255, 255));

        BackMD.setBackground(new java.awt.Color(204, 204, 255));
        BackMD.setText("Atras");
        BackMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMDActionPerformed(evt);
            }
        });
        BackMD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackMDKeyPressed(evt);
            }
        });
        BotonesMD.add(BackMD);

        Tabla.setBackground(new java.awt.Color(255, 255, 255));

        TablaMD.setBackground(new java.awt.Color(204, 255, 255));
        TablaMD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Merienda", "Garbanzos", "Alitas de pollo", "Macarrones", "Curry", "Espinacas", "Hamburguesa", "Tacos"},
                {"Cena", "Carne con tomate", "Pizza", "Ramen", "Lentejas", "Tortillas", "Sushi", null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"
            }
        ));
        jScrollPane1.setViewportView(TablaMD);

        javax.swing.GroupLayout TablaLayout = new javax.swing.GroupLayout(Tabla);
        Tabla.setLayout(TablaLayout);
        TablaLayout.setHorizontalGroup(
            TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        TablaLayout.setVerticalGroup(
            TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundMDLayout = new javax.swing.GroupLayout(BackgroundMD);
        BackgroundMD.setLayout(BackgroundMDLayout);
        BackgroundMDLayout.setHorizontalGroup(
            BackgroundMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundMDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(BackgroundMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundMDLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(BotonesMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );
        BackgroundMDLayout.setVerticalGroup(
            BackgroundMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundMDLayout.createSequentialGroup()
                .addComponent(Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(BackgroundMDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundMDLayout.createSequentialGroup()
                    .addContainerGap(159, Short.MAX_VALUE)
                    .addComponent(BotonesMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout MenuDiaLayout = new javax.swing.GroupLayout(MenuDia.getContentPane());
        MenuDia.getContentPane().setLayout(MenuDiaLayout);
        MenuDiaLayout.setHorizontalGroup(
            MenuDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuDiaLayout.setVerticalGroup(
            MenuDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDiaLayout.createSequentialGroup()
                .addComponent(BackgroundMD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setLayout(new java.awt.GridLayout(0, 1));

        Form.setText("Formulario");
        Form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormActionPerformed(evt);
            }
        });
        Menu.add(Form);

        DatosCliente.setText("Datos del Cliente");
        DatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosClienteActionPerformed(evt);
            }
        });
        Menu.add(DatosCliente);

        MenuRestaurante.setText("Menu del dia");
        MenuRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRestauranteActionPerformed(evt);
            }
        });
        Menu.add(MenuRestaurante);

        EmpresaButton.setText("Empresa");
        EmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpresaButtonActionPerformed(evt);
            }
        });
        Menu.add(EmpresaButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormActionPerformed

        FormDialog.setVisible(true);
        FormDialog.setSize(382, 200);
        dispose();
    }//GEN-LAST:event_FormActionPerformed

    private void DatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosClienteActionPerformed
        UserInformation.setVisible(true);
        UserInformation.setSize(900, 450);
        dispose();
    }//GEN-LAST:event_DatosClienteActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        MainPage mp = new MainPage();
        mp.setVisible(true);
        dispose();
        FormDialog.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked

    private void UserClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserClienteActionPerformed
      
    }//GEN-LAST:event_UserClienteActionPerformed

    private void BackUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackUIMouseClicked
        MainPage mp = new MainPage();
        mp.setVisible(true);
        dispose();
        UserInformation.setVisible(false);
    }//GEN-LAST:event_BackUIMouseClicked

    private void TextNombreUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreUIActionPerformed
       
    }//GEN-LAST:event_TextNombreUIActionPerformed

    private void EmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpresaButtonActionPerformed
        Empresa.setVisible(true);
        Empresa.setSize(642,526);
        dispose();
    }//GEN-LAST:event_EmpresaButtonActionPerformed

    private void BackCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackCTMouseClicked
        MainPage mp = new MainPage();
        mp.setVisible(true);
        dispose();
        Empresa.setVisible(false);
    }//GEN-LAST:event_BackCTMouseClicked

    private void BackCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackCTActionPerformed
  
    }//GEN-LAST:event_BackCTActionPerformed

    private void BackMDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackMDKeyPressed
          MainPage mp = new MainPage();
        mp.setVisible(true);
        dispose();
        MenuDia.setVisible(false);
    }//GEN-LAST:event_BackMDKeyPressed

    private void MenuRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRestauranteActionPerformed
           MenuDia.setVisible(true);
       MenuDia.setSize(978,216);
        dispose();
    }//GEN-LAST:event_MenuRestauranteActionPerformed

    private void BackMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMDActionPerformed
             MainPage mp = new MainPage();
        mp.setVisible(true);
        dispose();
        MenuDia.setVisible(false);
    }//GEN-LAST:event_BackMDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JLabel ApellidoUI;
    private javax.swing.JButton Back;
    private javax.swing.JButton BackCT;
    private javax.swing.JButton BackMD;
    private javax.swing.JButton BackUI;
    private javax.swing.JPanel BackgroundCT;
    private javax.swing.JPanel BackgroundFD;
    private javax.swing.JPanel BackgroundMD;
    private javax.swing.JPanel BackgroundUI;
    private javax.swing.JPanel BotonUI;
    private javax.swing.JPanel BotonesMD;
    private javax.swing.JPanel ButtonsFM;
    private java.awt.Label ComidasReparto;
    private javax.swing.JLabel CompanyName;
    private javax.swing.JButton DatosCliente;
    private javax.swing.JPanel DatosUI;
    private javax.swing.JLabel DireccionUI;
    private java.awt.Label Donaciones;
    private javax.swing.JLabel EmailUI;
    private javax.swing.JDialog Empresa;
    private javax.swing.JButton EmpresaButton;
    private javax.swing.JButton Form;
    private javax.swing.JDialog FormDialog;
    private javax.swing.JPanel FormTexts;
    private javax.swing.JPanel Menu;
    private javax.swing.JDialog MenuDia;
    private javax.swing.JButton MenuRestaurante;
    private javax.swing.JLabel NombreUI;
    private javax.swing.JLabel PassVar;
    private javax.swing.JPasswordField PasswordCliente;
    private java.awt.Label Realizamos;
    private javax.swing.JScrollPane ScrollTableCT;
    private javax.swing.JPanel Tabla;
    private javax.swing.JPanel TablaFull;
    private javax.swing.JTable TablaMD;
    private javax.swing.JTable TableCT;
    private java.awt.TextField TextApellidoUI;
    private java.awt.TextField TextDireccionUI;
    private java.awt.TextField TextEmaiUI;
    private java.awt.TextField TextNombreUI;
    private java.awt.TextField UserCliente;
    private javax.swing.JDialog UserInformation;
    private javax.swing.JLabel UserVar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
